name: Release workflow

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Set up MinGW
       uses: egor-tensin/setup-mingw@v2
       with:
         platform: i686
     - name: Compile
       run: |
         mingw32-make bossac
         mingw32-make strip-bossac
     - name: See bin directory
       run: ls bin
     - name: Move bin
       run: mv bin/ bossac/
     - name: Compress archive
       shell: pwsh
       run: Compress-Archive -Path bossac -DestinationPath bossac-windows.zip
     - uses: actions/upload-artifact@v2
       with:
         name: Windows
         path: bossac-windows.zip

  build-ubuntu:
    runs-on: ubuntu-18.04
    steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Compile
       run: |
         make bossac
         make strip-bossac
     - name: See bin directory
       run: ls bin
     - name: Move bin
       run: mv bin/ bossac/
     - name: Compress
       run: tar -cvjSf bossac-x86_64-linux-gnu.tar.bz2 bossac
     - uses: actions/upload-artifact@v2
       with:
         name: Ubuntu
         path: bossac-x86_64-linux-gnu.tar.gz


  build-ubuntu-i686:
    runs-on: ubuntu-18.04
    steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Install missing libs
       run: |
         sudo apt-get install gcc-multilib g++-multilib
     - name: Compile
       run: |
         export CXX_EXTRA=-m32
         make bossac
         make strip-bossac
     - name: See bin directory
       run: ls bin
     - name: Move bin
       run: mv bin/ bossac/
     - name: Compress
       run: tar -cvjSf bossac-i686-linux-gnu.tar.bz2 bossac
     - uses: actions/upload-artifact@v2
       with:
         name: Ubuntu-i686
         path: bossac-i686-linux-gnu.tar.gz



  build-macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Compile
        run: |
          make bossac
          make strip-bossac
      - name: See bin directory
        run: ls bin
      - name: Move bin
        run: mv bin/ bossac/
      - name: Compress
        run: tar -cvjSf bossac-apple-darwin.tar.bz2 bossac
      - uses: actions/upload-artifact@v2
        with:
          name: macOS
          path: bossac-apple-darwin.tar.gz
